"""add name column to social_media_links

Revision ID: 31c5c36fc530
Revises: a71f2e88903e
Create Date: 2024-08-02 00:50:09.518656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c5c36fc530'
down_revision: Union[str, None] = 'a71f2e88903e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Add column with default value for existing rows
    op.add_column('social_media_links', sa.Column('name', sa.String(), nullable=False, server_default='Unknown'))
    # Remove the default value for future inserts
    op.alter_column('social_media_links', 'name', server_default=None)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_media_links', 'name')
    # ### end Alembic commands ###
