"""Fix join condition and foreign keys

Revision ID: b1e032cffab1
Revises: 79abed546886
Create Date: 2024-07-28 04:22:47.449566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e032cffab1'
down_revision: Union[str, None] = '79abed546886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_social_media_links', sa.Column('profile_id', sa.UUID(), nullable=True))
    op.add_column('user_social_media_links', sa.Column('social_media_link_id', sa.UUID(), nullable=True))
    op.drop_constraint('user_social_media_links_user_id_fkey', 'user_social_media_links', type_='foreignkey')
    op.drop_constraint('user_social_media_links_social_meedia_link_id_fkey', 'user_social_media_links', type_='foreignkey')
    op.create_foreign_key(None, 'user_social_media_links', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'user_social_media_links', 'social_media_links', ['social_media_link_id'], ['id'])
    op.drop_column('user_social_media_links', 'user_id')
    op.drop_column('user_social_media_links', 'social_meedia_link_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_social_media_links', sa.Column('social_meedia_link_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('user_social_media_links', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_social_media_links', type_='foreignkey')
    op.drop_constraint(None, 'user_social_media_links', type_='foreignkey')
    op.create_foreign_key('user_social_media_links_social_meedia_link_id_fkey', 'user_social_media_links', 'social_media_links', ['social_meedia_link_id'], ['id'])
    op.create_foreign_key('user_social_media_links_user_id_fkey', 'user_social_media_links', 'users', ['user_id'], ['id'])
    op.drop_column('user_social_media_links', 'social_media_link_id')
    op.drop_column('user_social_media_links', 'profile_id')
    # ### end Alembic commands ###
