"""Updated models with forward declarations

Revision ID: bc39b227b065
Revises: bd955f35cc55
Create Date: 2024-07-28 21:02:00.818464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc39b227b065'
down_revision: Union[str, None] = 'bd955f35cc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('social_media_links', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('social_media_links', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('profiles', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
