"""Update models with AsyncAttrs2

Revision ID: bd955f35cc55
Revises: 3ab7d92af921
Create Date: 2024-07-28 04:51:29.171233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd955f35cc55'
down_revision: Union[str, None] = '3ab7d92af921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
